### ISSUE TITLE
Enable macvlan?

### ISSUE THREAD

**Issue by victornoel** [Excito/kernel-3.18#1]
Hi,

Any reason why macvlan is not enabled in b3's official kernel?

```
root@b3:~# zgrep macvlan /proc/config.gz 
# CONFIG_MACVLAN is not set
```

I was experimenting with network namespaces and had the need for it :)

I'm not sure if there is other similar modules that are related to this whole network namespaces business though... maybe there should be other to enable too?
I know VETH is an important one and it is enabled for example.

Thanks!

**Comment by MouettE-SC** [comment]
Hello,

I can add this option as a module and publish a newer version, no problem. Please make sure you don't need anything else though because it takes time and I don't want to do it several times in a row because you missed something ;-) .

**Comment by victornoel** [comment]
ok, so what I will do is look around and see if there is not some other modules that would good to enable too for these functionalities and get back to you! Thanks

**Comment by MouettE-SC** [comment]
So you know, I have another request in the forum for modules to be added in the kernel so I need to move forward on a new release. I will probably start working on in a day or two so. For now I'll add the macvlan module only, if you need more I'm all ears. In any case if something's missing I'll either make a new release or I'll help you compile your version.

**Comment by victornoel** [comment]
@MouettE-SC I guess you could also add the modules for BONDING, NET_TEAM (and the submodules), VXLAN, VETH, TUN, DUMMY too.

If you prefer not to add so much modules, I think at least VETH is commonly used in the kind of use case I was experimenting with (and I think I will have some use for it), as for the others, I think they could make sense.

(I'm not sure I managed to see the actual configuration used for bubba3… all of these were disabled when I did `make menuconfig` so maybe some of these are already enabled, TUN for example is :)

Thanks!

**Comment by MouettE-SC** [comment]
Version 1:3.18.48-1 released with the modules added. You can install it with apt-get update // apt-get upgrade as usual.

I'll close this, don't hesitate to comment more if your need.

**Comment by victornoel** [comment]
@MouettE-SC works great, thanks again!
